logs:
  - name: console # 控制台输出所有日志
    enable: true
    json: false # 不需要格式化为 json
    level: info
    output:
      type: console
      destination:
        filename: stdout
    encoderConfig:
      levelEncoder: capitalColor # 带颜色大写的日志级别 capital/capitalColor/color/lowcase
      timeEncoder: rfc3339nano # e.g.: 2006-01-02T15:04:05.999999999Z07:00 rfc3339nano/rfc3339/iso8601/millis/nanos/epoch
      durationEncoder: string # 时间段格式化为带单位的: 968.6µs string/nanos/ms/seconds or 带 layout 子字段
      callerEncoder: full # full/short
  - name: file # 输出到文件
    enable: true
    json: true
    level: debug
    output:
      type: file
      destination:
        filename: app.log
    encoderConfig:
      timeKey: time
      levelEncoder: capital
      timeEncoder:
        layout: "2006-01-03 15:04:06.000"
      durationEncoder: nanos
  - name: error-file # 只收集 error 日志
    enable: true
    json: true
    level: error
    output:
      type: file
      destination:
        filename: app.error.log
    encoderConfig:
      timeKey: time
      levelEncoder: capital
      timeEncoder: rfc3339nano
      durationEncoder: nanos
